id: 9aceac37-1d56-486a-88ff-5c7da42a380f
version: 9
name: Genians-Test
description: |-
  This playbook blocks malicious IPs using all integrations that are enabled.

  Supported integrations for this playbook:
  * Genian NAC
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: b95110b7-ba18-42a5-87ad-c5d37915401c
    type: start
    task:
      id: b95110b7-ba18-42a5-87ad-c5d37915401c
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 500,
          "y": 10
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 1808d949-f921-4957-8796-7bbedd822ad9
    type: title
    task:
      id: 1808d949-f921-4957-8796-7bbedd822ad9
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 500,
          "y": 1020
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 42389934-e0b1-4eec-88d8-c21d3b28e808
    type: title
    task:
      id: 42389934-e0b1-4eec-88d8-c21d3b28e808
      version: -1
      name: Block IPs
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "19"
      - "20"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 500,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: fed90fcf-42bb-4f0a-8ee6-2e863e24f0d4
    type: condition
    task:
      id: fed90fcf-42bb-4f0a-8ee6-2e863e24f0d4
      version: -1
      name: Is there an IP to block?
      description: Verify that the playbook input includes at least one IP to block.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: inputs.IP
            iscontext: true
    view: |-
      {
        "position": {
          "x": 500,
          "y": 145
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: 5a1ce507-df4d-45df-8eb4-26a1c0bb4304
    type: playbook
    task:
      id: 5a1ce507-df4d-45df-8eb4-26a1c0bb4304
      version: -1
      name: Add Indicator to Miner - Minemeld
      description: Add indicators to the relevant Miner using MineMeld.
      playbookName: Add Indicator to Miner - Palo Alto MineMeld
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      Indicator:
        complex:
          root: inputs.IP
      MinerName:
        complex:
          root: inputs.IPBlacklistMiner
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 500,
          "y": 660
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: 9a75be08-417a-4cf9-8298-2cb8bbdbc286
    type: condition
    task:
      id: 9a75be08-417a-4cf9-8298-2cb8bbdbc286
      version: -1
      name: Is Genian NAC enabled?
      description: Verify that there is a valid instance of Zscaler enabled.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: Zscaler
                    ignorecase: true
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                    ignorecase: true
                accessor: brand
            iscontext: true
          ignorecase: true
    view: |-
      {
        "position": {
          "x": 960,
          "y": 660
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 2fc91849-c0d9-4170-81b9-c53398a241df
    type: regular
    task:
      id: 2fc91849-c0d9-4170-81b9-c53398a241df
      version: -1
      name: Block IP with Genian NAC
      description: Assigns a tag to the Node specified.
      script: Genian NAC|||genian-nac-assign-ip-tag
      type: regular
      iscommand: true
      brand: Genian NAC
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      ip:
        complex:
          root: inputs.IP
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 960,
          "y": 850
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "19":
    id: "19"
    taskid: 53aee148-418c-49ad-8176-31c9ca887227
    type: title
    task:
      id: 53aee148-418c-49ad-8176-31c9ca887227
      version: -1
      name: MineMeld
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 500,
          "y": 515
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "20":
    id: "20"
    taskid: 8a74aeef-1b36-420f-815e-d30b19a1c002
    type: title
    task:
      id: 8a74aeef-1b36-420f-815e-d30b19a1c002
      version: -1
      name: Genian NAC
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 960,
          "y": 515
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {
      "12_2_#default#": 0.13,
      "8_2_#default#": 0.48
    },
    "paper": {
      "dimensions": {
        "height": 1075,
        "width": 840,
        "x": 500,
        "y": 10
      }
    }
  }
inputs:
- key: IP
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
outputs:
- contextPath: CheckpointFWRule.Destination
  description: Rule Destination.
- contextPath: CheckpointFWRule.DestinationNegate
  description: Rule destination negate status (True/False).
- contextPath: PanoramaRule.Direction
  description: Direction of the Panorama rule. Can be 'to','from', 'both'
  type: string
- contextPath: PanoramaRule.IP
  description: The IP the Panorama rule blocks
  type: string
- contextPath: CheckpointFWRule.Name
  description: Rule name.
- contextPath: PanoramaRule.Name
  description: Name of the Panorama rule
  type: string
- contextPath: CheckpointFWRule.UID
  description: Rule UID.
- contextPath: PanoramaRule
  description: List of Panorama rules
- contextPath: CheckpointFWRule.Type
  description: Rule Type.
- contextPath: CheckpointFWRule.Action
  description: 'Rule action (Valid values are: Accept, Drop, Apply Layer, Ask, Info).'
- contextPath: CheckpointFWRule.ActionSetting
  description: Rule action settings.
- contextPath: CheckpointFWRule.CustomFields
  description: Rule custom fields.
- contextPath: CheckpointFWRule.Data
  description: Rule data.
- contextPath: CheckpointFWRule.DataDirection
  description: Rule data direction.
- contextPath: CheckpointFWRule.DataNegate
  description: Rule data negate status (True/False).
- contextPath: CheckpointFWRule.Domain
  description: Rule domain.
- contextPath: CheckpointFWRule.Enabled
  description: Rule status.
- contextPath: CheckpointFWRule.Hits
  description: Rule hits count.
- contextPath: CheckpointFWRule.Data.Name
  description: Rule data object name.
- contextPath: CheckpointFWRule.Data.Domain
  description: Information about the domain the data object belongs to.
- contextPath: CheckpointFWRule.Domain.Name
  description: Rule domain name.
- contextPath: CheckpointFWRule.Domain.UID
  description: Rule domain UID.
- contextPath: CheckpointFWRule.Domain.Type
  description: Rule domain type.
- contextPath: CheckpointFWRule.Hits.FirstDate
  description: The date of the first hit for the rule.
- contextPath: CheckpointFWRule.Hits.LastDate
  description: The date of the last hit for the rule.
- contextPath: CheckpointFWRule.Hits.Level
  description: Level of rule hits.
- contextPath: CheckpointFWRule.Hits.Percentage
  description: Percentage of rule hits.
- contextPath: CheckpointFWRule.Hits.Value
  description: Value of rule hits.
sourceplaybookid: Block IP - Generic v2
